### ISSUE TITLE
How to Use in Android Studio

### ISSUE THREAD

**Issue by cmoore1711** [Digidemic/UnitOf#6]
Is there a line that can be used in build.gradle as an implementaion to use this in my Android Studio Project? Android Studio Artic Fox 2020.3.1 Thanks!

**Comment by Digidemic** [comment]
Only a couple of years late addressing this issue 😁 
As of now, UnitOf can be installed with JitPack. Installation guide can be found here: https://github.com/Digidemic/UnitOf?tab=readme-ov-file#jitpack--buildgradle
